name: check-style

on:
  push:
    branches: [ main, tc-l2 ]

jobs:
  check-style:
    name: Check Code Style
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "fake action"